# Generated by Django 4.0.5 on 2022-07-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='no_hours',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
