# Generated by Django 4.0.5 on 2022-07-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='comment',
            new_name='comment_id',
        ),
    ]
