# Generated by Django 4.0.5 on 2022-07-04 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='session',
        ),
        migrations.AddField(
            model_name='comment',
            name='session',
            field=models.ManyToManyField(related_name='session', to='app.session'),
        ),
    ]
