# Generated by Django 4.0.5 on 2022-07-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='profile',
            name='modules',
            field=models.ManyToManyField(blank=True, to='app.module'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date_of_session',
            field=models.DateTimeField(),
        ),
    ]
