# Generated by Django 4.0.5 on 2022-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_session_no_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='no_hours',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
