# Generated by Django 4.0.5 on 2022-07-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_session_no_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='no_hours',
            field=models.PositiveSmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
