# Generated by Django 4.0.5 on 2022-07-05 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_comment_likes_alter_comment_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='app.session'),
        ),
    ]
