# Generated by Django 4.0.5 on 2022-07-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_comment_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='no_hours',
        ),
    ]
