# Generated by Django 4.0.5 on 2022-07-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_comment_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
